global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'don@t1techworks.com'
    from: 'contact@disruptivecoding.com'
    smarthost: 'server:port'
    auth_username: 'emailname'
    auth_identity: 'emailname'
    auth_password: 'password'
    tls_config:
           insecure_skip_verify: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']